title: <p align="center"> Tanaya Modak </p>
logo: assets/logo.png

description:
  
  <a href="https://www.linkedin.co/in/tanaya-modak-28870517a/">LinkedIn</a> |
  <a href="https://github.com/modaktanaya">GitHub</a>
  
  <br>   
  I'm student pursuing Master's in Machine Learning and AI.
  I have completed my Bachelor's in Computer Science and working on Data Science and ML projects.
  <br>
  
theme: jekyll-theme-minimal
